In [1]:
import numpy as np

In [2]:
ones = np.ones(4)

In [3]:
ones

array([1., 1., 1., 1.])

In [4]:
ones.reshape(4,1)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [5]:
zeros = np.zeros(4)

In [6]:
zeros

array([0., 0., 0., 0.])

In [7]:
all_stack = np.hstack([ones.reshape(4,1),zeros.reshape(4,1)])

In [8]:
all_stack

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [9]:
all_stack = np.vstack([ones.reshape(4,1),zeros.reshape(4,1)])

In [10]:
all_stack

array([[1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
w1 = -0.1
w2 = -0.15
b = 0
parameters = np.matrix([w1,w2,b]).T

In [12]:
parameters

matrix([[-0.1 ],
        [-0.15],
        [ 0.  ]])

In [13]:
np.matrix([w1,w2,b]).reshape(3,1)

matrix([[-0.1 ],
        [-0.15],
        [ 0.  ]])

In [14]:
np.matrix([w1,w2,b])

matrix([[-0.1 , -0.15,  0.  ]])

In [15]:
np.matrix([w1,w2,b]).T

matrix([[-0.1 ],
        [-0.15],
        [ 0.  ]])