In [2]:
y = ([0,1,2,3,4])

In [4]:
import numpy as np

In [5]:
x = np.asarray(y)

In [39]:
type(x)

numpy.ndarray

In [15]:
type(x)

numpy.ndarray

In [16]:
from keras.utils import to_categorical

In [25]:
cate = to_categorical(x,5)

In [26]:
cate.shape

(5, 5)

In [27]:
x.shape

(5,)

In [30]:
cate[0]

array([1., 0., 0., 0., 0.], dtype=float32)

In [36]:
for i in range(5):
    print(cate[i])

[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]


In [42]:
print(x)
print(cate)

[0 1 2 3 4]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
print(x.shape)
print(cate.shape)

(5,)
(5, 5)


In [44]:
wtf = to_categorical(x,10)

In [45]:
print(wtf)
print(wtf.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
(5, 10)


In [46]:
x_2 = np.asarray([1,3,5,7,9])

In [47]:
x_2

array([1, 3, 5, 7, 9])

In [48]:
cate_2 = to_categorical(x_2,10)

In [49]:
cate_2

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)